In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df_ct = pd.read_csv('CardTransaction.csv')
df_ct.head(10)

,TransactionId,CardNumber,LotNumber,NoEntry,NoExit,Overnight,EntranceTime,ExitTime,EffectiveGroupNumber
0,1284656,19835,10,0,0,1,2020-12-31 16:29:30.0000000,2021-01-01 01:03:21.0000000,80
1,1284658,4377,21,1,0,0,NaN,2021-01-01 08:34:31.0000000,-1
2,1284659,10662,21,1,0,0,NaN,2021-01-01 09:38:30.0000000,-1
3,1284663,10662,21,0,0,0,2021-01-01 12:31:44.0000000,2021-01-01 13:16:59.0000000,-1
4,1284667,24172,21,0,0,0,2021-01-01 14:07:08.0000000,2021-01-01 15:01:53.0000000,24
5,1284674,41137,97,1,0,0,NaN,2021-01-02 06:26:17.0000000,-1
6,1284750,22155,80,0,1,0,2021-01-02 07:11:25.0000000,NaN,-1
7,1284753,22155,70,0,1,0,2021-01-02 07:19:05.0000000,NaN,-1
8,1284755,33525,80,0,1,0,2021-01-02 06:58:35.0000000,NaN,81
9,1284757,22155,50,0,1,0,2021-01-02 07:21:45.0000000,NaN,-1

In [ ]:
df_ct.dtypes

TransactionId            int64
CardNumber               int64
LotNumber                int64
NoEntry                  int64
NoExit                   int64
Overnight                int64
EntranceTime            object
ExitTime                object
EffectiveGroupNumber     int64
dtype: object

In [ ]:
print(f"Total rows: {df_ct.shape[0]}")

Total rows: 4246646

In [ ]:
df_ct = df_ct[df_ct["EffectiveGroupNumber"] != -1]

In [ ]:
print(f"Total rows: {df_ct.shape[0]}")

Total rows: 3830759

In [ ]:
df_ct["EntranceTime"] = pd.to_datetime(df_ct["EntranceTime"], errors='coerce')
df_ct["ExitTime"] = pd.to_datetime(df_ct["ExitTime"], errors='coerce')
df_ct.dtypes

TransactionId                    int64
CardNumber                       int64
LotNumber                        int64
NoEntry                          int64
NoExit                           int64
Overnight                        int64
EntranceTime            datetime64[ns]
ExitTime                datetime64[ns]
EffectiveGroupNumber             int64
dtype: object

In [ ]:
# Filling missing ExitTime
df_ct["ExitTime"] = df_ct.apply(
    lambda row: pd.Timestamp(row["EntranceTime"].date()) + pd.Timedelta(days=1)
    if pd.isna(row["ExitTime"]) and pd.notna(row["EntranceTime"])
    else row["ExitTime"],
    axis=1
)

# Filling missing EntranceTime
df_ct["EntranceTime"] = df_ct.apply(
    lambda row: pd.Timestamp(row["ExitTime"].date())
    if pd.isna(row["EntranceTime"]) and pd.notna(row["ExitTime"])
    else row["EntranceTime"],
    axis=1
)

In [ ]:
df_ct.head(10)

,TransactionId,CardNumber,LotNumber,NoEntry,NoExit,Overnight,EntranceTime,ExitTime,EffectiveGroupNumber
0,1284656,19835,10,0,0,1,2020-12-31 16:29:30,2021-01-01 01:03:21,80
4,1284667,24172,21,0,0,0,2021-01-01 14:07:08,2021-01-01 15:01:53,24
8,1284755,33525,80,0,1,0,2021-01-02 06:58:35,2021-01-03 00:00:00,81
12,1284776,38446,10,0,1,0,2021-01-02 07:34:59,2021-01-03 00:00:00,85
15,1284801,38446,11,0,1,0,2021-01-02 08:17:04,2021-01-03 00:00:00,85
17,1284811,45013,10,0,1,0,2021-01-02 06:59:13,2021-01-03 00:00:00,85
25,1284845,47471,50,0,1,0,2021-01-02 06:38:03,2021-01-03 00:00:00,76
26,1284847,20594,10,0,1,0,2021-01-02 09:46:41,2021-01-03 00:00:00,81
27,1284856,32871,11,0,1,0,2021-01-02 08:30:35,2021-01-03 00:00:00,81
28,1284863,38624,10,0,1,0,2021-01-02 09:41:38,2021-01-03 00:00:00,2

In [ ]:
# Extract Month, Year, Day, Week components from EntranceTime
df_ct["EntryYear"] = df_ct["EntranceTime"].dt.year
df_ct["EntryMonth"] = df_ct["EntranceTime"].dt.month
df_ct["EntryDay"] = df_ct["EntranceTime"].dt.day
df_ct["EntryDate"] = df_ct["EntranceTime"].dt.date
df_ct["EntryWeek"] = df_ct["EntranceTime"].dt.isocalendar().week
df_ct["EntryTime"] = df_ct["EntranceTime"].dt.time
df_ct["EntryDayOfWeek"] = df_ct["EntranceTime"].dt.day_name()

# Extract Month, Year, Day, Week components from ExitTime
df_ct["ExitYear"] = df_ct["ExitTime"].dt.year
df_ct["ExitMonth"] = df_ct["ExitTime"].dt.month
df_ct["ExitDay"] = df_ct["ExitTime"].dt.day
df_ct["ExitDate"] = df_ct["ExitTime"].dt.date
df_ct["ExitWeek"] = df_ct["ExitTime"].dt.isocalendar().week
df_ct["ExitTimeOnly"] = df_ct["ExitTime"].dt.time
df_ct["ExitDayOfWeek"] = df_ct["ExitTime"].dt.day_name()

In [ ]:
pd.set_option('display.max_columns', None)
df_ct.head(10)

,TransactionId,CardNumber,LotNumber,NoEntry,NoExit,Overnight,EntranceTime,ExitTime,EffectiveGroupNumber,EntryYear,EntryMonth,EntryDay,EntryDate,EntryWeek,EntryTime,EntryDayOfWeek,ExitYear,ExitMonth,ExitDay,ExitDate,ExitWeek,ExitTimeOnly,ExitDayOfWeek,ParkingDurationHours
0,1284656,19835,10,0,0,1,2020-12-31 16:29:30,2021-01-01 01:03:21,80,2020,12,31,2020-12-31,53,16:29:30,Thursday,2021,1,1,2021-01-01,53,01:03:21,Friday,8.56
4,1284667,24172,21,0,0,0,2021-01-01 14:07:08,2021-01-01 15:01:53,24,2021,1,1,2021-01-01,53,14:07:08,Friday,2021,1,1,2021-01-01,53,15:01:53,Friday,0.91
8,1284755,33525,80,0,1,0,2021-01-02 06:58:35,2021-01-03 00:00:00,81,2021,1,2,2021-01-02,53,06:58:35,Saturday,2021,1,3,2021-01-03,53,00:00:00,Sunday,17.02
12,1284776,38446,10,0,1,0,2021-01-02 07:34:59,2021-01-03 00:00:00,85,2021,1,2,2021-01-02,53,07:34:59,Saturday,2021,1,3,2021-01-03,53,00:00:00,Sunday,16.42
15,1284801,38446,11,0,1,0,2021-01-02 08:17:04,2021-01-03 00:00:00,85,2021,1,2,2021-01-02,53,08:17:04,Saturday,2021,1,3,2021-01-03,53,00:00:00,Sunday,15.72
17,1284811,45013,10,0,1,0,2021-01-02 06:59:13,2021-01-03 00:00:00,85,2021,1,2,2021-01-02,53,06:59:13,Saturday,2021,1,3,2021-01-03,53,00:00:00,Sunday,17.01
25,1284845,47471,50,0,1,0,2021-01-02 06:38:03,2021-01-03 00:00:00,76,2021,1,2,2021-01-02,53,06:38:03,Saturday,2021,1,3,2021-01-03,53,00:00:00,Sunday,17.37
26,1284847,20594,10,0,1,0,2021-01-02 09:46:41,2021-01-03 00:00:00,81,2021,1,2,2021-01-02,53,09:46:41,Saturday,2021,1,3,2021-01-03,53,00:00:00,Sunday,14.22
27,1284856,32871,11,0,1,0,2021-01-02 08:30:35,2021-01-03 00:00:00,81,2021,1,2,2021-01-02,53,08:30:35,Saturday,2021,1,3,2021-01-03,53,00:00:00,Sunday,15.49
28,1284863,38624,10,0,1,0,2021-01-02 09:41:38,2021-01-03 00:00:00,2,2021,1,2,2021-01-02,53,09:41:38,Saturday,2021,1,3,2021-01-03,53,00:00:00,Sunday,14.31

In [ ]:
# Calculate parking duration in hours and round to 2 decimals
df_ct["ParkingDurationHours"] = (pd.to_datetime(df_ct["ExitTime"]) - pd.to_datetime(df_ct["EntranceTime"])).dt.total_seconds() / 3600
df_ct["ParkingDurationHours"] = df_ct["ParkingDurationHours"].round(2)

In [ ]:
print("Number of rows where NoExit == 1:", (df_ct["NoExit"] == 1).sum())
print("Number of rows where NoEntry == 1:", (df_ct["NoEntry"] == 1).sum())

Number of rows where NoExit == 1: 205748
Number of rows where NoEntry == 1: 121753

In [ ]:
df_ct.to_csv("Cleaned_CardTransaction.csv", index=False)

### **Creating a 'PeakUsageByDay' csv file from the Cleaned_CardTransaction.csv by calculating simultaneous usage of each parking lot and displaying the peak hour of every lot, everyday**

In [ ]:
df_cl = pd.read_csv('Cleaned_CardTransaction.csv')
pd.set_option('display.max_columns', None)
df_cl.head(10)

,TransactionId,CardNumber,LotNumber,NoEntry,NoExit,Overnight,EntranceTime,ExitTime,EffectiveGroupNumber,EntryYear,EntryMonth,EntryDay,EntryDate,EntryWeek,EntryTime,EntryDayOfWeek,ExitYear,ExitMonth,ExitDay,ExitDate,ExitWeek,ExitTimeOnly,ExitDayOfWeek,ParkingDurationHours
0,1284656,19835,10,0,0,1,2020-12-31 16:29:30,2021-01-01 01:03:21,80,2020,12,31,2020-12-31,53,16:29:30,Thursday,2021,1,1,2021-01-01,53,01:03:21,Friday,8.56
1,1284667,24172,21,0,0,0,2021-01-01 14:07:08,2021-01-01 15:01:53,24,2021,1,1,2021-01-01,53,14:07:08,Friday,2021,1,1,2021-01-01,53,15:01:53,Friday,0.91
2,1284755,33525,80,0,1,0,2021-01-02 06:58:35,2021-01-03 00:00:00,81,2021,1,2,2021-01-02,53,06:58:35,Saturday,2021,1,3,2021-01-03,53,00:00:00,Sunday,17.02
3,1284776,38446,10,0,1,0,2021-01-02 07:34:59,2021-01-03 00:00:00,85,2021,1,2,2021-01-02,53,07:34:59,Saturday,2021,1,3,2021-01-03,53,00:00:00,Sunday,16.42
4,1284801,38446,11,0,1,0,2021-01-02 08:17:04,2021-01-03 00:00:00,85,2021,1,2,2021-01-02,53,08:17:04,Saturday,2021,1,3,2021-01-03,53,00:00:00,Sunday,15.72
5,1284811,45013,10,0,1,0,2021-01-02 06:59:13,2021-01-03 00:00:00,85,2021,1,2,2021-01-02,53,06:59:13,Saturday,2021,1,3,2021-01-03,53,00:00:00,Sunday,17.01
6,1284845,47471,50,0,1,0,2021-01-02 06:38:03,2021-01-03 00:00:00,76,2021,1,2,2021-01-02,53,06:38:03,Saturday,2021,1,3,2021-01-03,53,00:00:00,Sunday,17.37
7,1284847,20594,10,0,1,0,2021-01-02 09:46:41,2021-01-03 00:00:00,81,2021,1,2,2021-01-02,53,09:46:41,Saturday,2021,1,3,2021-01-03,53,00:00:00,Sunday,14.22
8,1284856,32871,11,0,1,0,2021-01-02 08:30:35,2021-01-03 00:00:00,81,2021,1,2,2021-01-02,53,08:30:35,Saturday,2021,1,3,2021-01-03,53,00:00:00,Sunday,15.49
9,1284863,38624,10,0,1,0,2021-01-02 09:41:38,2021-01-03 00:00:00,2,2021,1,2,2021-01-02,53,09:41:38,Saturday,2021,1,3,2021-01-03,53,00:00:00,Sunday,14.31

In [ ]:

df_cl["EntranceTime"] = pd.to_datetime(df_cl["EntranceTime"], format='mixed')
df_cl["ExitTime"] = pd.to_datetime(df_cl["ExitTime"], format='mixed')


# Round Entrance and Exit to the hour
df_cl["EntranceHour"] = df_cl["EntranceTime"].dt.floor("H")
df_cl["ExitHour"] = df_cl["ExitTime"].dt.floor("H")

# Generate list of hourly timestamps each car was present
df_cl["HourList"] = df_cl.apply(
    lambda row: pd.date_range(start=row["EntranceHour"], end=row["ExitHour"], freq="H"), axis=1
)

# Explode rows so each hour becomes a new row
df_expanded = df_cl.explode("HourList")

# Extract hour and date for grouping
df_expanded["Hour"] = df_expanded["HourList"].dt.hour
df_expanded["Date"] = pd.to_datetime(df_expanded["EntryDate"])  # use your existing date col

# Count simultaneous users
simultaneous_usage = (
    df_expanded.groupby(["LotNumber", "Date", "Hour"])["CardNumber"]
    .nunique()
    .reset_index(name="SimultaneousUsers")
)

# Get the hour with the highest usage for each lot per day
peak_by_day = (
    simultaneous_usage.sort_values(["LotNumber", "Date", "SimultaneousUsers"], ascending=[True, True, False])
    .drop_duplicates(["LotNumber", "Date"])
    .reset_index(drop=True)
)

# Add readable range
peak_by_day["PeakTimeRange"] = peak_by_day["Hour"].astype(str) + ":00 - " + (peak_by_day["Hour"] + 1).astype(str) + ":00"


peak_by_day.to_csv("PeakUsageByDay.csv", index=False)

<ipython-input-6-ca127715e204>:7: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df_cl["EntranceHour"] = df_cl["EntranceTime"].dt.floor("H")
<ipython-input-6-ca127715e204>:8: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df_cl["ExitHour"] = df_cl["ExitTime"].dt.floor("H")
<ipython-input-6-ca127715e204>:12: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lambda row: pd.date_range(start=row["EntranceHour"], end=row["ExitHour"], freq="H"), axis=1

In [ ]:
#PeakUsageByDay for all the dates was crashing my runtime due to insufficient RAM, therefore I decided to create a 'Cleaned_CardTransaction_2024.csv' which had 2024 data only and ran the Peak Usage code on that file

df_cl["EntranceTime"] = pd.to_datetime(df_cl["EntranceTime"], format='mixed')
df_cl["ExitTime"] = pd.to_datetime(df_cl["ExitTime"], format='mixed')
df_cl = df_cl[df_cl["EntranceTime"].dt.year == 2024]

In [ ]:
df_cl.to_csv("Cleaned_CardTransaction_2024.csv", index=False)

In [ ]:
df_cl2 = pd.read_csv('Cleaned_CardTransaction_2024.csv')

In [ ]:

df_cl2["EntranceTime"] = pd.to_datetime(df_cl2["EntranceTime"], format='mixed')
df_cl2["ExitTime"] = pd.to_datetime(df_cl2["ExitTime"], format='mixed')


df_cl2["EntranceHour"] = df_cl2["EntranceTime"].dt.floor("H")
df_cl2["ExitHour"] = df_cl2["ExitTime"].dt.floor("H")


df_cl2["HourList"] = df_cl2.apply(
    lambda row: pd.date_range(start=row["EntranceHour"], end=row["ExitHour"], freq="H"), axis=1
)

df_expanded = df_cl2.explode("HourList")

df_expanded["Hour"] = df_expanded["HourList"].dt.hour
df_expanded["Date"] = pd.to_datetime(df_expanded["EntryDate"])


simultaneous_usage = (
    df_expanded.groupby(["LotNumber", "Date", "Hour"])["CardNumber"]
    .nunique()
    .reset_index(name="SimultaneousUsers")
)

peak_by_day = (
    simultaneous_usage.sort_values(["LotNumber", "Date", "SimultaneousUsers"], ascending=[True, True, False])
    .drop_duplicates(["LotNumber", "Date"])
    .reset_index(drop=True)
)

peak_by_day["PeakTimeRange"] = peak_by_day["Hour"].astype(str) + ":00 - " + (peak_by_day["Hour"] + 1).astype(str) + ":00"


peak_by_day.to_csv("PeakUsageByDay_2024.csv", index=False)

<ipython-input-9-d59ca5b8f321>:7: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df_cl2["EntranceHour"] = df_cl2["EntranceTime"].dt.floor("H")
<ipython-input-9-d59ca5b8f321>:8: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df_cl2["ExitHour"] = df_cl2["ExitTime"].dt.floor("H")
<ipython-input-9-d59ca5b8f321>:12: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lambda row: pd.date_range(start=row["EntranceHour"], end=row["ExitHour"], freq="H"), axis=1

In [2]:
#used data from April 2024 to April 2025 to predict forecast of remaining months on Tableau

df_cl5 = pd.read_csv('Cleaned_CardTransaction.csv')
df_cl5["EntranceTime"] = pd.to_datetime(df_cl5["EntranceTime"], format='mixed')

# Define the date range
start_date = pd.Timestamp("2024-04-30")
end_date = pd.Timestamp("2025-04-30")


df_cl5 = df_cl5[(df_cl5["EntranceTime"] >= start_date) & (df_cl5["EntranceTime"] <= end_date)]

df_cl5.to_csv("Cleaned_CardTransaction_2025.csv", index=False)

In [1]:
df_cl5 = pd.read_csv('Cleaned_CardTransaction_2025.csv')
df_cl5["EntranceTime"] = pd.to_datetime(df_cl5["EntranceTime"], format='mixed')
df_cl5["ExitTime"] = pd.to_datetime(df_cl5["ExitTime"], format='mixed')


df_cl5["EntranceHour"] = df_cl5["EntranceTime"].dt.floor("H")
df_cl5["ExitHour"] = df_cl5["ExitTime"].dt.floor("H")

df_cl5["HourList"] = df_cl5.apply(
    lambda row: pd.date_range(start=row["EntranceHour"], end=row["ExitHour"], freq="H"), axis=1
)


df_expanded = df_cl5.explode("HourList")

df_expanded["Hour"] = df_expanded["HourList"].dt.hour
df_expanded["Date"] = pd.to_datetime(df_expanded["EntryDate"])  # use your existing date col

simultaneous_usage = (
    df_expanded.groupby(["LotNumber", "Date", "Hour"])["CardNumber"]
    .nunique()
    .reset_index(name="SimultaneousUsers")
)

peak_by_day = (
    simultaneous_usage.sort_values(["LotNumber", "Date", "SimultaneousUsers"], ascending=[True, True, False])
    .drop_duplicates(["LotNumber", "Date"])
    .reset_index(drop=True)
)

peak_by_day["PeakTimeRange"] = peak_by_day["Hour"].astype(str) + ":00 - " + (peak_by_day["Hour"] + 1).astype(str) + ":00"

peak_by_day.to_csv("PeakUsageByDay_2025.csv", index=False)

<ipython-input-1-1c2c647145fe>:8: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df_cl5["EntranceHour"] = df_cl5["EntranceTime"].dt.floor("H")
<ipython-input-1-1c2c647145fe>:9: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df_cl5["ExitHour"] = df_cl5["ExitTime"].dt.floor("H")
<ipython-input-1-1c2c647145fe>:13: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  lambda row: pd.date_range(start=row["EntranceHour"], end=row["ExitHour"], freq="H"), axis=1